name: Go Benchmark Test

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  go-benchmark-checks:
    name: GoBenchmark
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Go test
        run: go test ./... -v
